version: 2
executorType: machine
stages:
  build:
    workDir: ~/pdftk-deb
    steps:
      - type: shell
        name: Prep /development
        command: |
          sudo mkdir /development
          sudo chmod 777 /development
          ln -s /home/circleci/redis-deb /development/redis-deb
      - type: checkout
      - type: shell
        name: Build image
        command: |
          cd trusty
          docker-compose build
          docker-compose run redis
      - type: shell
        name: Run tests
        command: |
          cd trusty
          docker-compose run test
#      - type: shell
#        name: Upload package
#        command: aws s3 cp ~/pdftk-deb/trusty/out/pdftk_2.02-4-trusty-talis_amd64.deb s3://aspire-operations/binaries/aptly/pdftk_2.02-4-trusty-talis_amd64.deb
